version: "3"

services:
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/nginx.html:/data/www/index.html
      - ./public:/data/www/public
    environment:
      ENV: development
      VIRTUAL_PORT: 80
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: photography-website
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      ENV: develoment
      PORT: 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
