version: "3"

services:
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx:/etc/nginx/conf.d
      - ./infra/nginx/nginx.html:/var/www/html/index.html
      - ./public:/var/www/html
    environment:
      ENV: development
      VIRTUAL_PORT: 3000
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: photography-website
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    environment:
      ENV: develoment
      SERVICE_NAME: app
      VIRTUAL_PROTO: http
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
