# TODO: deploy like https://testdriven.io/blog/deploying-django-to-digitalocean-with-docker-and-github-actions/
name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: main_server

jobs:
  terraform:
    name: "Digital Ocean Terraform deploy"
    runs-on: ubuntu-latest
    env:
      TF_WORKDIR: terraform/environments/digital-ocean.production.fra1
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_domain_url: ${{ secrets.DOMAIN }}
      TF_VAR_root_password: ${{ secrets.DO_ROOT_PASSWORD }}
      TF_VAR_ssh_fingerprint: ${{ secrets.DO_SSH_FINGERPRINT }}
      TF_VAR_pvt_key: ${{ secrets.DO_SSH_SECRET_KEY }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.DO_TOKEN }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init
          -backend-config="access_key=${{secrets.DO_SPACES_ACCESS_KEY}}"
          -backend-config="secret_key=${{secrets.DO_SPACES_SECRET_KEY}}"

      # - name: Terraform Format
      #   working-directory: ${{ env.TF_WORKDIR }}
      #   run: terraform fmt -check
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKDIR }}
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest

          terraform plan \
            -var "docker_image_id=$IMAGE_ID:$VERSION" \
            -var "github_token=${{ secrets.GITHUB_TOKEN }}" \
            -var "github_user=${{ github.actor }}"

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKDIR }}
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest

          terraform apply -auto-approve \
            -var "docker_image_id=$IMAGE_ID:$VERSION" \
            -var "github_token=${{ secrets.GITHUB_TOKEN }}" \
            -var "github_user=${{ github.actor }}"
